### PR TITLE
Implement `--restore-table-mapping` for `restore` and `restore_remote`

### LINKED ISSUE #937: Implementation --restore-table-mapping
It looks like the tool doesn't support restoring a table backup to a table with a different name. In clickhouse, we can do this by using the `[AS [db.]table_name_in_backup]` clause in the `RESTORE TABLE`. For the restore related commands, we can have an option similar to `--restore-database-mapping` which can be used to accomplish this.

### PR DESCRIPTION
**Pull request by nithin-vunet**
Hi,
This PR implements `--restore-table-mapping` for restore commands like `restore` and `restore_remote` 

fix #937

### CODE REVIEW

**Comment by Slach** [comment]
thanks for contribution

almost looks good
but we definitely need to pass integration tests

first of all
```
rm -f ./test/testflows/clickhouse_backup/tests/snapshots/cli.py.cli.snapshot
cp -v ./test/testflows/.env.example ./test/testflows/.env
change required environment variables
bash -xe ./test/testflows/run.sh
```

then clean all containers
```
for id in $(docker ps -a -q); do docker stop "$id"; docker rm -f "$id"; done;
```

and run
```
cp -v ./test/integration/.env.example ./test/integration/.env
./test/integration/run.sh
```
it requires docker and docker-compose

change `./test/integration/integration_test.go` add 
`TestRestoreTableMapping` similar with `TestRestoreDatabaseMapping`
or rename `TestRestoreDatabaseMapping` to `TestRestoreMapping` and extend it to cover --restore-table-mapping use cases

**Review by Slach — CHANGES_REQUESTED** [review]
need pass to integration tests

**Comment by nithin-vunet** [comment]
```bash
cp -v ./test/integration/.env.example ./test/integration/.env
./test/integration/run.sh
```
When I run the integration tests, `clickhouse` server doesn't go healthy at all.
I figured it is due to the below volume map for `clickhouse` container.
```
      - ./dynamic_settings.sh:/docker-entrypoint-initdb.d/dynamic_settings.sh
```

Any idea what could be done?

**Comment by nithin-vunet** [comment]
Also noticed that the `testflows` are failing, specifically at the `gcs` backup flows. Are these due to the code changes?

**Comment by Slach** [comment]
> cp -v ./test/integration/.env.example ./test/integration/.env

It will not work
you need to provide actual for variables values

**Comment by Slach** [comment]
> Also noticed that the testflows are failing, specifically at the gcs backup flows. Are these due to the code changes?

these tests just requires 
provide
./test/testflows/.env

look to 
./test/testflows/.env.example

you need provide actual values

**Comment by Slach** [comment]
ok. let me fix testflows failures after change default config

**Comment by nithin-vunet** [comment]
Where I do find the actual values to enter in the `env` file?

**Comment by Slach** [comment]
@nithin-vunet
ok. now testflows tests passed
 
for integration test you could just create empty `./test/integration/.env`

and run following command
```
CLICKHOUSE_VERSION=1.1.54394 LOG_LEVEL=debug RUN_TESTS=TestRestoreDatabaseMapping ./test/integration/run.sh
```

Distributed table `d1` not restored properly and still reference to `database1`, because you changed regexp
here
https://github.com/Altinity/clickhouse-backup/pull/944/files#diff-e97997e8a71f01e4c09b9c689c4b1153f1aa283f98fb86b55971577c70cb8a13R304


```
2024/07/03 17:10:36.613524  info Check result database-2
2024/07/03 17:10:36.613561 debug SELECT count() FROM `database-2`.t1 logger=integration-test
2024/07/03 17:10:36.623627 debug SELECT count() FROM `database-2`.d1 logger=integration-test
    integration_test.go:2198:
                Error Trace:    /home/slach/src/github.com/altinity/clickhouse-backup/test/integration/integration_test.go:2198
                                                        /home/slach/src/github.com/altinity/clickhouse-backup/test/integration/integration_test.go:2240
                Error:          Received unexpected error:
                                code: 81, message: Database database1 doesn't exist
                Test:           TestRestoreDatabaseMapping
```

**Comment by nithin-vunet** [comment]
@Slach Thanks for the instructions. I was able to fix the failed checks. Updated `TestRestoreDatabaseMapping` to `TestRestoreMapping` to include test for table mappings as well.

**Review by Slach — APPROVED** [review]

**Comment by nithin-vunet** [comment]
@raspreet-vunet thanks for your contribution and inspiration

**Pull request merged**
