### PR TITLE
draft: update clickhouse-go to v2

### PR DESCRIPTION
**Pull request by anikin-aa**
Update clickhouse-go module to v2. Fix integration tests according to new contract from the lib

### CODE REVIEW

**Comment by anikin-aa** [comment]
local build is ok, unit tests are also OK. will try launch integration tests today and share the results

**Comment by Slach** [comment]
Integration tests failed
look details
here
https://github.com/AlexAkulov/clickhouse-backup/actions/runs/3434851457/jobs/5814860566#step:7:2539
and here
https://github.com/AlexAkulov/clickhouse-backup/actions/runs/3434851457/jobs/5814860928#step:7:110

Could you change `/test/integration/integration_test.go` for use `clickhouse-go/v2`?

**Review by Slach — CHANGES_REQUESTED** [review]
could we return error in `chbackend.Query` after switch to v2?

**Comment by anikin-aa** [comment]
> Could you change /test/integration/integration_test.go for use clickhouse-go/v2?

yep, i've missed this file, working on it 

> could we return error in chbackend.Query after switch to v2?

https://github.com/anikin-aa/clickhouse-backup/blob/clickhouse-go/v2/pkg/clickhouse/clickhouse.go#L724-L726 error already returned, need to do changes in `/test/integration/integration_test.go`

**Comment by Slach** [comment]
@anikin-aa any progress?

**Comment by anikin-aa** [comment]
@Slach , hi !
new changes has been committed, local tests are passed

```
PASS
ok  	command-line-arguments	214.196s
```

there is one ugly part here: https://github.com/anikin-aa/clickhouse-backup/blob/clickhouse-go/v2/test/integration/integration_test.go#L1713-L1726

my be you could suggest better approach ?

**Comment by Slach** [comment]
;(( 
looks like clickhouse-go v2 doesn't work with old clickhouse-server version ;(
https://github.com/AlexAkulov/clickhouse-backup/actions/runs/3529409950/jobs/5925048227#step:7:120

Don't sure we should to approve this PR in this case
which improvements it will add to main use cases?

Maybe we should switch from native to http protocol?

**Comment by anikin-aa** [comment]
> which improvements it will add to main use cases?

Not so much to be honest, just take the latest available library  

> Maybe we should switch from native to http protocol?

http right now set as experimental for clickhouse-go https://github.com/ClickHouse/clickhouse-go#https-experimental

I will try to check what's possible to do with old ch versions

**Comment by Slach** [comment]
@anikin-aa 
maybe after merge https://github.com/ClickHouse/clickhouse-go/pull/975
next release clickhouse-go should works with old clickhouse versions

**Comment by Slach** [comment]
lets wait and resolve conflicts

**Comment by Slach** [comment]
lookg progress https://github.com/Altinity/clickhouse-backup/pull/669

**Pull request closed without merging**
