### PR TITLE
SFTP/SSH storage support

### PR DESCRIPTION
**Pull request by ComBin**
Hello! Our company using access to backup storage via SSH. I implements support this storage in this pull request. If all ok you can merge it. If somethin wrong i can make the required improvements. I tried to make the minimum changes outside the file  pkg/new_storage/ssh.go, but couldn't do without a pair of crutches in pkg/new_storage/general.go:

- [Different delete method](https://github.com/AlexAkulov/clickhouse-backup/compare/master...combin:master#diff-9c5056d7fc01eb67fc70a65dfc2762293dc45062af4c56ca600dcaf562f5d9bcR63) cause ordinary walk does not fit for deleting file on file system, you must delete file in folder prior deleting folder, but default walk returns files/folders in not suitable sequence.
- [NotExist error](https://github.com/AlexAkulov/clickhouse-backup/compare/master...combin:master#diff-9c5056d7fc01eb67fc70a65dfc2762293dc45062af4c56ca600dcaf562f5d9bcL201) cause lib that i use return different error when file not exists.

### CODE REVIEW

**Comment by Slach** [comment]
@combin could you add some integration test to ensure ssh will always works?
look to  https://github.com/AlexAkulov/clickhouse-backup/tree/master/test/integration
and try to add https://github.com/linuxserver/docker-openssh-server into docker-compose*.yaml  files

**Comment by ComBin** [comment]
Sure.

**Comment by ComBin** [comment]
@Slach, integration tests is ready. I dont known in what cases this conditions `if os.Getenv("SSH_TESTS") == "" || os.Getenv("TRAVIS_PULL_REQUEST") != "false" {` is needed, uncomment if must have.

**Comment by AlexAkulov** [comment]
Please resolve conflicts and rename SSH to SFTP for clarity.

**Comment by ComBin** [comment]
Done.

**Comment by AlexAkulov** [comment]
Thank you!

**Comment by ComBin** [comment]
Looks like some issue with permission of key on testing server. I make some change in compose file this should fix.

**Pull request merged**
