### PR TITLE
Allow custom S3 storage class

### PR DESCRIPTION
**Pull request by realwhite**

### CODE REVIEW

**Comment by Slach** [comment]
which s3 compatible API do you use for test?

**Comment by realwhite** [comment]
@Slach Hi, we a cloud provider (https://mcs.mail.ru/) and we provide S3 compatible API. Our S3 has a storage class BACKUP (it's more cheap then STANDARD)

**Comment by Slach** [comment]
thank you so much for contribution, let's wait tests

**Comment by Slach** [comment]
try to `rm -fv ./test/testsflows/clickhouse_backup/tests/snapshots/cli.py.cli.snapshot` 
after it re-run testflows manually
look to `./tests/testflows/README.md` for details how

if you can't looks like we can merge this PR without testflows

**Pull request merged**
