### PR TITLE
Support of ManagedIdentity azure auth

### PR DESCRIPTION
**Pull request by roman-vynar**
First of all, thanks for such a great tool!

We are using this tool with both AWS S3 and Azure blob storage.

AWS S3 works ok with IAM Instance Role permissions associated with an instance, w/o using any static keys.

However, with Azure the tool only works with Storage Account access keys (not really secure method, providing full access to SA, the keys are static and so on) or SAS tokens (which are not flexible to use and insecure the way Azure implemented them).

There are 2 other methods to access Azure blob storage: OAuth credentials of AD app registrations (tenant id + app id + client secret token) or using ManagedIdentity. 

The last one is nice because it can work with SystemAssigned Identity associated with a VM, much like Instance Role with AWS. You can grant an access to a specific container within Storage Account to a service principal of a single VM without using any kind of credentials or static keys.

Adding this simple PR to be able to use ManagedIdentity. Just grant access and set "use_managed_identity: true".

### CODE REVIEW

**Comment by rhuddleston** [comment]
Fixes https://github.com/AlexAkulov/clickhouse-backup/issues/197

**Comment by Slach** [comment]
@rhuddleston great contribution thanks a lot

How did you test it?
Did you try to change azure config on `./tests/intergations/config-azure.yaml` 
and run `AZURE_TESTS=1 bash -xe ./tests/intergations/run.sh`?

**Comment by roman-vynar** [comment]
Hello, I have tested this straight on our environment, on Azure VM and it works ok.

My config:
```
azblob:
  endpoint_suffix:      core.windows.net
  account_name:         foobar
  account_key:          ""
  sas:                  ""
  use_managed_identity: true
  container:            backups-clickhouse
  path:                 "clickhouse/binary"
  compression_level:    1
  compression_format:   gzip
  sse_key:              ""
```

Here is how do I grant the access for dbnode1 to "backups-clickhouse" container in "foobar" storage account using Terraform Azure plugin:
```
data "azurerm_storage_container" "backups_cont" {
  name                 = "backups-clickhouse"
  storage_account_name = "foobar"
}

resource "azurerm_role_assignment" "dbnode_backup_access" {
  scope                = data.azurerm_storage_container.backups_cont.resource_manager_id
  role_definition_name = "Storage Blob Data Owner"
  principal_id         = azurerm_linux_virtual_machine.dbnode1.identity[0].principal_id
}
```

**Comment by roman-vynar** [comment]
Thank you!

**Pull request merged**
